# Generated by Django 5.0.2 on 2024-03-21 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.TextField()),
                ('habit_name', models.CharField(max_length=255)),
                ('is_habit_practiced', models.BooleanField(default=False)),
                ('tracking_name', models.CharField(max_length=255)),
                ('tracking_value', models.FloatField()),
                ('goal_name', models.CharField(max_length=255)),
                ('is_goal_done', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
