# Generated by Django 5.0.2 on 2024-04-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_type', models.TextField(default=False)),
                ('tracking_name', models.CharField(max_length=255)),
                ('habit_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='journal',
            name='goal_name',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='habit_name',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='is_goal_done',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='tracking_name',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
    ]
