# Generated by Django 5.0.2 on 2024-04-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0002_goal_header_remove_journal_goal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_done',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='header',
            name='highlight_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_habit_practiced',
            field=models.BooleanField(),
        ),
    ]
